=== franzlst/PbD_FRI/motion_control/cartesian_motion_control/cpf/cpf.dtd
<!ELEMENT properties (description? , (simple|sequence|struct)* )>
<!ELEMENT choice (#PCDATA)>
<!ELEMENT choices (choice+)>
<!ELEMENT defaultvalue (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT simple (description?, value, choices?, defaultvalue?)>
<!ATTLIST simple name CDATA #IMPLIED type (boolean|char|double|float|short|long|objref|octet|string|ulong|ushort) #REQUIRED>
<!ELEMENT sequence (description?, (simple*|struct*|sequence*))>
<!ATTLIST sequence name CDATA #IMPLIED type CDATA #REQUIRED>
<!ELEMENT struct (description?, (simple|sequence|struct)*)>
<!ATTLIST struct name CDATA #IMPLIED type CDATA #REQUIRED>
<!ELEMENT value (#PCDATA)>

=== franzlst/PbD_FRI/motion_control/cartesian_motion_control/cartesian-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "cpf.dtd">
<properties>
<simple name="Import" type="string"><value>/usr/lib/orocos</value></simple>

<struct name="CartesianControllerPosVel" type="OCL::CartesianControllerPosVel">
  <struct name="Activity" type="PeriodicActivity">
    <simple name="Period" type="double"><value>0.01</value></simple>
    <simple name="Priority" type="short"><value>0</value></simple>
    <simple name="Scheduler" type="string"><value>ORO_SCHED_RT</value></simple>
  </struct>
  <simple name="AutoConf" type="boolean"><value>1</value></simple>
  <simple name="AutoStart" type="boolean"><value>0</value></simple>
  <simple name="PropertyFile" type="string"><value>cpf/CartesianControllerPosVel.cpf</value></simple>
  <struct name="Ports" type="PropertyBag">
     <simple name="CartesianSensorPosition" type="string"><value>CartesianSensorPosition</value></simple>
     <simple name="CartesianDesiredPosition" type="string"><value>CartesianDesiredPosition</value></simple>
     <simple name="CartesianDesiredVelocity" type="string"><value>CartesianDesiredVelocity</value></simple>
     <simple name="CartesianOutputVelocity" type="string"><value>CartesianOutputVelocity</value></simple>
  </struct>
</struct>

<struct name="CartesianGeneratorPos" type="OCL::CartesianGeneratorPos">
  <struct name="Activity" type="PeriodicActivity">
    <simple name="Period" type="double"><value>0.01</value></simple>
    <simple name="Priority" type="short"><value>0</value></simple>
    <simple name="Scheduler" type="string"><value>ORO_SCHED_RT</value></simple>
  </struct>
  <simple name="AutoConf" type="boolean"><value>1</value></simple>
  <simple name="AutoStart" type="boolean"><value>0</value></simple>
  <simple name="PropertyFile" type="string"><value>cpf/CartesianGeneratorPos.cpf</value></simple>
  <struct name="Ports" type="PropertyBag">
     <simple name="CartesianSensorPosition" type="string"><value>CartesianSensorPosition</value></simple>
     <simple name="CartesianDesiredVelocity" type="string"><value>CartesianDesiredVelocity</value></simple>
     <simple name="CartesianDesiredPosition" type="string"><value>CartesianDesiredPosition</value></simple>
  </struct>
</struct>

<struct name="CartesianRobot" type="OCL::CartesianVelocityController">
  <struct name="Activity" type="PeriodicActivity">
    <simple name="Period" type="double"><value>0.01</value></simple>
    <simple name="Priority" type="short"><value>0</value></simple>
    <simple name="Scheduler" type="string"><value>ORO_SCHED_RT</value></simple>
  </struct>
  <simple name="AutoConf" type="boolean"><value>1</value></simple>
  <simple name="AutoStart" type="boolean"><value>1</value></simple>
  <simple name="PropertyFile" type="string"><value>cpf/CartesianRobot.cpf</value></simple>
  <struct name="Ports" type="PropertyBag">
     <simple name="CartesianOutputVelocity" type="string"><value>CartesianOutputVelocity</value></simple>
     <simple name="CartesianSensorPosition" type="string"><value>CartesianSensorPosition</value></simple>
     <simple name="nAxesSensorPosition" type="string"><value>nAxesSensorPosition</value></simple>
     <simple name="nAxesOutputVelocity" type="string"><value>nAxesOutputVelocity</value></simple>
  </struct>
  <struct name="Peers" type="PropertyBag">
     <simple type="string"><value>Robot</value></simple>
     <simple type="string"><value>CartesianGeneratorPos</value></simple>
     <simple type="string"><value>CartesianControllerPosVel</value></simple>
  </struct>
  <simple name="StateMachineScript" type="string"><value>cpf/states.osd</value></simple>
</struct>


<struct name="Robot" type="OCL::Kuka361nAxesVelocityController">
  <struct name="Activity" type="PeriodicActivity">
    <simple name="Period" type="double"><value>0.001</value></simple>
    <simple name="Priority" type="short"><value>0</value></simple>
    <simple name="Scheduler" type="string"><value>ORO_SCHED_RT</value></simple>
  </struct> 
  <simple name="AutoConf" type="boolean"><value>1</value></simple>
  <simple name="AutoStart" type="boolean"><value>1</value></simple>
  <simple name="PropertyFile" type="string"><value>cpf/Kuka361VelocityController.cpf</value></simple>
  <struct name="Ports" type="PropertyBag">
     <simple name="nAxesSensorPosition" type="string"><value>nAxesSensorPosition</value></simple>
     <simple name="nAxesOutputVelocity" type="string"><value>nAxesOutputVelocity</value></simple>
  </struct>
</struct>
</properties>

=== franzlst/PbD_FRI/kuka_robot_hardware/lwr_fri/example/test_LWR_naxes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "cpf.dtd">
<properties>

	<simple name="Import" type="string"><value>rtt_rosnode</value></simple>
	<simple name="Import" type="string"><value>ocl</value></simple>
	<simple name="Import" 
type="string"><value>naxes_motion_control</value></simple>
	<simple name="Import" type="string"><value>lwr_fri</value></simple>

	<struct name="FRIServer" type="lwr_fri::FRIComponent">
		<struct name="Activity" type="NonPeriodicActivity">
			<simple name="Priority" type="long"><value>1</value></simple>
			<simple name="Scheduler" type="string"><value>ORO_SCHED_RT</value></simple>
		</struct>
		<simple name="AutoConf" type="boolean"><value>1</value></simple>
		<simple name="AutoStart" type="boolean"><value>1</value></simple>
		<simple name="LoadProperties" 
type="string"><value>cpf/FRIServer.cpf</value></simple>
		<struct name="Ports" type="PropertyBag">
			<simple name="JointState" type="string"><value>JntPosMsr</value></simple>
			<simple name="JointPositionCommand" type="string"><value>JntPosDsr</value></simple>
			<!--<simple name="FRIState" type="string"><value>FRIStatus</value></simple>-->
		</struct>
	</struct>

	<struct name="nAxesGeneratorPos" type="MotionControl::nAxesGeneratorPos">
		<struct name="Activity" type="PeriodicActivity">
			<simple name="Period" type="double"><value>0.01</value></simple>
			<simple name="Priority" type="long"><value>1</value></simple>
			<simple name="Scheduler" type="string"><value>ORO_SCHED_RT</value></simple>
		</struct>
		<simple name="AutoConf" type="boolean"><value>1</value></simple>
		<simple name="AutoStart" type="boolean"><value>1</value></simple>
		<simple name="PropertyFile" 
type="string"><value>cpf/nAxesGeneratorPos.cpf</value></simple>
		<struct name="Ports" type="PropertyBag">
			<simple name="nAxesSensorPosition" 
type="string"><value>JntPosMsr</value></simple>
			<simple name="nAxesDesiredPosition" 
type="string"><value>JntPosDsr</value></simple>
		</struct>
	</struct>


	<struct name="Reporter" type="OCL::FileReporting"> 
		<struct name="Activity" type="PeriodicActivity"> 
			<simple name="Period" type="double"><value>0.04</value></simple> 
			<simple name="Priority" type="short"><value>1</value></simple> 
			<simple name="Scheduler" type="string"><value>ORO_SCHED_OTHER</value></simple>
		</struct>
		<simple name="AutoConf" type="boolean"><value>1</value></simple>
		<simple name="AutoStart" type="boolean"><value>1</value></simple>
		<simple name="AutoSave" type="boolean"><value>0</value></simple>
		<simple name="LoadProperties" type="string"><value>cpf/reporter_naxes.cpf</value></simple>
		<struct name="Peers" type="PropertyBag">
			<simple name="Peer" type="string"><value>FRIServer</value></simple>
			<simple name="Peer" type="string"><value>nAxesGeneratorPos</value></simple>
		</struct>
	</struct>

</properties>

=== franzlst/PbD_FRI/motion_control/naxes_motion_control/naxes-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "cpf.dtd">
<properties>
<simple name="Import" type="string"><value>/install/build-trunk-lxrt/lib</value></simple>

<struct name="nAxesControllerPos" type="OCL::nAxesControllerPos">
  <struct name="Activity" type="PeriodicActivity">
    <simple name="Period" type="double"><value>0.01</value></simple>
    <simple name="Priority" type="short"><value>0</value></simple>
    <simple name="Scheduler" type="string"><value>ORO_SCHED_RT</value></simple>
  </struct>
  <simple name="AutoConf" type="boolean"><value>1</value></simple>
  <simple name="AutoStart" type="boolean"><value>0</value></simple>
  <simple name="PropertyFile" type="string"><value>cpf/nAxesControllerPos.cpf</value></simple>
  <struct name="Ports" type="PropertyBag">
     <simple name="nAxesSensorPosition" type="string"><value>nAxesSensorPosition</value></simple>
     <simple name="nAxesDesiredPosition" type="string"><value>nAxesDesiredPosition</value></simple>
     <simple name="nAxesOutputVelocity" type="string"><value>nAxesOutputVelocity</value></simple>
  </struct>
</struct>

<struct name="nAxesControllerPosVel" type="OCL::nAxesControllerPosVel">
  <struct name="Activity" type="PeriodicActivity">
    <simple name="Period" type="double"><value>0.01</value></simple>
    <simple name="Priority" type="short"><value>0</value></simple>
    <simple name="Scheduler" type="string"><value>ORO_SCHED_RT</value></simple>
  </struct>
  <simple name="AutoConf" type="boolean"><value>1</value></simple>
  <simple name="AutoStart" type="boolean"><value>0</value></simple>
  <simple name="PropertyFile" type="string"><value>cpf/nAxesControllerPosVel.cpf</value></simple>
  <struct name="Ports" type="PropertyBag">
     <simple name="nAxesSensorPosition" type="string"><value>nAxesSensorPosition</value></simple>
     <simple name="nAxesDesiredPosition" type="string"><value>nAxesDesiredPosition</value></simple>
     <simple name="nAxesDesiredVelocity" type="string"><value>nAxesDesiredVelocity</value></simple>
     <simple name="nAxesOutputVelocity" type="string"><value>nAxesOutputVelocity</value></simple>
  </struct>
</struct>

<struct name="nAxesControllerVel" type="OCL::nAxesControllerVel">
  <struct name="Activity" type="PeriodicActivity">
    <simple name="Period" type="double"><value>0.01</value></simple>
    <simple name="Priority" type="short"><value>0</value></simple>
    <simple name="Scheduler" type="string"><value>ORO_SCHED_RT</value></simple>
  </struct>
  <simple name="AutoConf" type="boolean"><value>1</value></simple>
  <simple name="AutoStart" type="boolean"><value>0</value></simple>
  <simple name="PropertyFile" type="string"><value>cpf/nAxesControllerVel.cpf</value></simple>
  <struct name="Ports" type="PropertyBag">
     <simple name="nAxesSensorPosition" type="string"><value>nAxesSensorPosition</value></simple>
     <simple name="nAxesDesiredVelocity" type="string"><value>nAxesDesiredVelocity</value></simple>
     <simple name="nAxesOutputVelocity" type="string"><value>nAxesOutputVelocity</value></simple>
  </struct>
</struct>

<struct name="nAxesGeneratorPos" type="OCL::nAxesGeneratorPos">
  <struct name="Activity" type="PeriodicActivity">
    <simple name="Period" type="double"><value>0.01</value></simple>
    <simple name="Priority" type="short"><value>0</value></simple>
    <simple name="Scheduler" type="string"><value>ORO_SCHED_RT</value></simple>
  </struct>
  <simple name="AutoConf" type="boolean"><value>1</value></simple>
  <simple name="AutoStart" type="boolean"><value>0</value></simple>
  <simple name="PropertyFile" type="string"><value>cpf/nAxesGeneratorPos.cpf</value></simple>
  <struct name="Ports" type="PropertyBag">
     <simple name="nAxesSensorPosition" type="string"><value>nAxesSensorPosition</value></simple>
     <simple name="nAxesDesiredVelocity" type="string"><value>nAxesDesiredVelocity</value></simple>
     <simple name="nAxesDesiredPosition" type="string"><value>nAxesDesiredPosition</value></simple>
  </struct>
</struct>


<struct name="Robot" type="OCL::nAxesVelocityController">
  <struct name="Activity" type="PeriodicActivity">
    <simple name="Period" type="double"><value>0.001</value></simple>
    <simple name="Priority" type="short"><value>0</value></simple>
    <simple name="Scheduler" type="string"><value>ORO_SCHED_RT</value></simple>
  </struct> 
  <simple name="AutoConf" type="boolean"><value>1</value></simple>
  <simple name="AutoStart" type="boolean"><value>1</value></simple>
  <simple name="PropertyFile" type="string"><value>cpf/nAxesVelocityController.cpf</value></simple>
  <struct name="Ports" type="PropertyBag">
     <simple name="nAxesSensorPosition" type="string"><value>nAxesSensorPosition</value></simple>
     <simple name="nAxesSensorVelocity" type="string"><value>nAxesSensorVelocity</value></simple>
     <simple name="nAxesOutputValue" type="string"><value>nAxesOutputVelocity</value></simple>
  </struct>
</struct>
</properties>

=== franzlst/PbD_FRI/basic_moves/setup_basic_moves.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "cpf.dtd">
<properties>

	<simple name="Import" type="string"><value>rtt_rosnode</value></simple>
	<simple name="Import" type="string"><value>ocl</value></simple>
	<simple name="Import" type="string"><value>naxes_motion_control</value></simple>
	<simple name="Import" type="string"><value>lwr_fri</value></simple>
	<simple name="Import" type="string"><value>basic_moves</value></simple>

	<struct name="FRIServer" type="lwr_fri::FRIComponent">
		<struct name="Activity" type="NonPeriodicActivity">
			<simple name="Priority" type="long"><value>1</value></simple>
			<simple name="Scheduler" type="string"><value>ORO_SCHED_RT</value></simple>
		</struct>
		<simple name="AutoConf" type="boolean"><value>1</value></simple>
		<simple name="AutoStart" type="boolean"><value>1</value></simple>
		<simple name="LoadProperties" 
type="string"><value>../kuka_robot_hardware/lwr_fri/example/cpf/FRIServer.cpf</value></simple>
		<struct name="Ports" type="PropertyBag">
			<simple name="JointState" type="string"><value>JntPosMsr</value></simple>
			<simple name="JointPositionCommand" type="string"><value>JntPosDsr</value></simple>
			<simple name="CartesianPosition" type="string"><value>CartPos</value></simple>
			<simple name="FRIState" type="string"><value>FRIState</value></simple>
			<simple name="RobotState" type="string"><value>RobotState</value></simple>
		</struct>
	</struct>

	<struct name="nAxesGeneratorPos" type="MotionControl::nAxesGeneratorPos">
		<struct name="Activity" type="PeriodicActivity">
			<simple name="Period" type="double"><value>0.01</value></simple>
			<simple name="Priority" type="long"><value>1</value></simple>
			<simple name="Scheduler" type="string"><value>ORO_SCHED_RT</value></simple>
		</struct>
		<simple name="AutoConf" type="boolean"><value>1</value></simple>
		<simple name="AutoStart" type="boolean"><value>1</value></simple>
		<simple name="PropertyFile" 
type="string"><value>../kuka_robot_hardware/lwr_fri/example/cpf/nAxesGeneratorPosT2.cpf</value></simple>
		<struct name="Ports" type="PropertyBag">
			<simple name="nAxesSensorPosition" type="string"><value>JntPosMsr</value></simple>
			<simple name="nAxesDesiredPosition" type="string"><value>JntPosDsr</value></simple>
			<simple name="events" type="string"><value>AxesEvents</value></simple>
		</struct>
	</struct>

	<struct name="BasicMoves" type="iros::Basic_moves">
		<struct name="Activity" type="NonPeriodicActivity">
			<simple name="Priority" type="long"><value>1</value></simple>
			<simple name="Scheduler" type="string"><value>ORO_SCHED_RT</value></simple>
		</struct>
		<simple name="AutoConf" type="boolean"><value>1</value></simple>
		<simple name="AutoStart" type="boolean"><value>1</value></simple>
		<!--<simple name="LoadProperties" type="string"><value>cpf/FRIServer.cpf</value></simple>-->
		<struct name="Ports" type="PropertyBag">
			<simple name="JointsPort" type="string"><value>JntPosMsr</value></simple>
			<simple name="PosePort" type="string"><value>CartPos</value></simple>
			<simple name="AxesEventPort" type="string"><value>AxesEvents</value></simple>
			<simple name="FRIState" type="string"><value>FRIState</value></simple>
			<simple name="RobotState" type="string"><value>RobotState</value></simple>
		</struct>
		<struct name="Peers" type="PropertyBag">
			<simple name="Peer" type="string"><value>nAxesGeneratorPos</value></simple>
		</struct>
	</struct>


	<!--<struct name="Reporter" type="OCL::FileReporting"> 
		<struct name="Activity" type="PeriodicActivity"> 
			<simple name="Period" type="double"><value>0.04</value></simple> 
			<simple name="Priority" type="short"><value>1</value></simple> 
			<simple name="Scheduler" type="string"><value>ORO_SCHED_OTHER</value></simple>
		</struct>
		<simple name="AutoConf" type="boolean"><value>1</value></simple>
		<simple name="AutoStart" type="boolean"><value>1</value></simple>
		<simple name="AutoSave" type="boolean"><value>0</value></simple>
		<simple name="LoadProperties" type="string"><value>cpf/reporter_naxes.cpf</value></simple>
		<struct name="Peers" type="PropertyBag">
			<simple name="Peer" type="string"><value>FRIServer</value></simple>
			<simple name="Peer" type="string"><value>nAxesGeneratorPos</value></simple>
		</struct>
	</struct>-->

</properties>
